spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?characterEncoding=utf-8&useSell=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
env: test234
